import Foundation

// WARNING:
// This code is generated by ./Scripts/generate-secrets.sh.
// Do not edit this file directly. Your changes will be lost on next run.
// Git does not track this file.
// Instead, edit the .env file and run ./Scripts/generate-secrets.sh

// swiftlint:disable all

/// Secrets are generated from .env by ./Scripts/generate-secrets.sh
enum Secrets {
    static let PRIVY_APP_ID = "cm98lzjet01acky0jv85xqpmc"
    static let PRIVY_APP_SECRET = "5ZnNNx59w2BrZRY2MQ5JpTkz5SsjCs4gHuZseGQtvCSLt9PfwVH4CAQ6CETYCDuywrgawuhrYAmk6kKGqNWFkyoX"
    static let PRIVY_APP_CLIENT_ID = "client-WY5ijkibZV41XZQbAQoaf1nvpWMbkFcXofEGBtSz4EgAN"
    static let POSTHOG_API_KEY = "phc_zKMKiWKcxHhQkOHacUNbItAsFQxtRrlM3Dz7PWwenvA"
    static let POSTHOG_HOST = "https://us.i.posthog.com"
    static let SENTRY_DSN = "https://642e08b75922b47bbe197c2ed6b4b7a7@o4504757119680512.ingest.us.sentry.io/4509175441063936"
    static let SENTRY_UPLOAD_SYMBOLS_AUTH_TOKEN = "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"
    static let SENTRY_ORG = "ephemerahq"
    static let SENTRY_PROJECT = "apple-ios"
}

// swiftlint:enable all
