#!/usr/bin/env bash

set -e
set -o pipefail
# NO set -x to avoid exposing secrets in logs

# Source shared utility functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/secrets-utils.sh"

SECRETS_FILE="Convos/Config/Secrets.swift"
APPCLIP_SECRETS_FILE="ConvosAppClip/Config/Secrets.swift"

echo "🔑 Generating Secrets.swift from environment variables"

# CONVOS_API_BASE_URL and XMTP_CUSTOM_HOST are optional (can be empty)

# Create directories if needed
ensure_secrets_directories

# Escape values to prevent injection
ESCAPED_API_URL=$(swift_escape "${CONVOS_API_BASE_URL:-}")
ESCAPED_XMTP_HOST=$(swift_escape "${XMTP_CUSTOM_HOST:-}")
ESCAPED_GATEWAY_URL=$(swift_escape "${GATEWAY_URL:-}")

# Handle Sentry DSN - use SENTRY_DSN_DEV for dev builds, empty for prod
if [[ -n "${SENTRY_DSN_DEV}" ]]; then
    ESCAPED_SENTRY_DSN=$(swift_escape "${SENTRY_DSN_DEV}")
elif [[ -n "${SENTRY_DSN_PROD}" ]]; then
    ESCAPED_SENTRY_DSN=""
    echo "🚫 Production build detected - Sentry DSN explicitly disabled"
else
    ESCAPED_SENTRY_DSN=$(swift_escape "${SENTRY_DSN:-}")
fi

# Generate Secrets.swift WITHOUT exposing values in logs
cat >"$SECRETS_FILE" <<EOF
import Foundation

// WARNING:
// This code is generated by ./Scripts/generate-secrets-secure.sh.
// Do not edit this file directly. Your changes will be lost on next run.
// Git does not track this file.

/// Secrets are generated from environment variables by ./Scripts/generate-secrets-secure.sh
enum Secrets {
    static let CONVOS_API_BASE_URL: String = "$ESCAPED_API_URL"
    static let XMTP_CUSTOM_HOST: String = "$ESCAPED_XMTP_HOST"
    static let GATEWAY_URL: String = "$ESCAPED_GATEWAY_URL"
    static let SENTRY_DSN: String = "$ESCAPED_SENTRY_DSN"
}
EOF

# Copy the generated file to ConvosAppClip
cp "$SECRETS_FILE" "$APPCLIP_SECRETS_FILE"

echo "✅ Generated Secrets.swift with configuration:"

# Display values
if [[ -z "$CONVOS_API_BASE_URL" ]]; then
    echo "  - CONVOS_API_BASE_URL: (empty - will use default from config.json)"
else
    echo "  - CONVOS_API_BASE_URL: $CONVOS_API_BASE_URL"
fi

if [[ -z "$XMTP_CUSTOM_HOST" ]]; then
    echo "  - XMTP_CUSTOM_HOST: (empty - will use default)"
else
    echo "  - XMTP_CUSTOM_HOST: $XMTP_CUSTOM_HOST"
fi

if [[ -z "$GATEWAY_URL" ]]; then
    echo "  - GATEWAY_URL: (empty - will use direct XMTP connection)"
else
    echo "  - GATEWAY_URL: $GATEWAY_URL"
fi

if [[ -n "$ESCAPED_SENTRY_DSN" ]]; then
    echo "  - SENTRY_DSN: (configured - not displayed for security)"
else
    echo "  - SENTRY_DSN: (empty - Sentry disabled)"
fi

echo ""
echo "🔐 Secrets.swift generated successfully at:"
echo "   - $SECRETS_FILE"
echo "   - $APPCLIP_SECRETS_FILE"
