#!/usr/bin/env bash

# Exit on any error and ensure pipeline failures are caught
set -e
set -o pipefail

# This script generates the Secrets.swift file for Local development
# It automatically detects the local IP address and populates the secrets
# It also ensures the file exists with minimal content if needed
# Usage: ./generate-secrets-local.sh

# The path to the Secrets.swift file
SECRETS_FILE="Convos/Config/Secrets.swift"

# Create the output directory if it doesn't exist
mkdir -p "Convos/Config"

# Function to create minimal Secrets.swift if it doesn't exist or is empty
ensure_minimal_secrets() {
    if [ ! -f "$SECRETS_FILE" ] || [ ! -s "$SECRETS_FILE" ]; then
        echo "🔑 Creating minimal Secrets.swift file first"

        cat >"$SECRETS_FILE" <<'MINIMAL_EOF'
import Foundation

// WARNING:
// This is a minimal Secrets.swift file created automatically.
// Building the "Convos (Local)" scheme will replace this with auto-detected IP addresses.

// swiftlint:disable all

enum Secrets {
    static let CONVOS_API_BASE_URL = ""
    static let XMTP_CUSTOM_HOST = ""
    static let FIREBASE_APP_CHECK_TOKEN = ""
    static let TURNKEY_PUBLIC_ORGANIZATION_ID = ""
    static let TURNKEY_API_PUBLIC_KEY = ""
    static let TURNKEY_API_PRIVATE_KEY = ""
    static let TURNKEY_PUBLIC_BASE_URL = ""
    static let POSTHOG_API_KEY = ""
    static let POSTHOG_HOST = ""
    static let SENTRY_DSN = ""
    static let SENTRY_UPLOAD_SYMBOLS_AUTH_TOKEN = ""
    static let SENTRY_ORG = ""
    static let SENTRY_PROJECT = ""
    static let SLACK_URL_WITH_KEY = ""
    static let PASSKEY_API_BASE_URL = ""
}

// swiftlint:enable all
MINIMAL_EOF
        echo "✅ Created minimal Secrets.swift file"
        return 0
    fi
    return 1
}

# If called with --ensure-only flag, just ensure minimal file exists and exit
if [ "$1" = "--ensure-only" ]; then
    if ensure_minimal_secrets; then
        echo "✅ Minimal Secrets.swift created - ready for building"
    else
        echo "✅ Secrets.swift already exists"
    fi
    exit 0
fi

echo "🔍 Detecting local IP address for Local development..."

# Ensure minimal file exists first (in case this is the first run)
ensure_minimal_secrets || true  # Don't exit if file already exists

# Function to get the first routable IPv4 address
get_local_ip() {
    # Get all network interfaces and find the first routable IPv4 address
    # Exclude:
    # - 127.x.x.x (loopback)
    # - 169.254.x.x (link-local/APIPA - indicates DHCP failure)
    # - 0.0.0.0 (invalid)
    # Prefer in order:
    # 1. Public IP addresses (not in private ranges)
    # 2. Private network addresses (10.x.x.x, 172.16-31.x.x, 192.168.x.x)

    # First try to get a public IP (not in private ranges)
    local public_ip=$(ifconfig | grep -E "inet [0-9]+" | \
        grep -v "127\." | \
        grep -v "169\.254\." | \
        grep -v "10\." | \
        grep -v "172\.1[6-9]\." | \
        grep -v "172\.2[0-9]\." | \
        grep -v "172\.3[0-1]\." | \
        grep -v "192\.168\." | \
        head -1 | awk '{print $2}')

    if [ -n "$public_ip" ]; then
        echo "$public_ip"
        return
    fi

    # If no public IP, get the first private network IP (but not link-local)
    local private_ip=$(ifconfig | grep -E "inet [0-9]+" | \
        grep -v "127\." | \
        grep -v "169\.254\." | \
        head -1 | awk '{print $2}')

    echo "$private_ip"
}

# Detect the local IP
LOCAL_IP=$(get_local_ip)

if [ -z "$LOCAL_IP" ]; then
    echo "❌ Could not detect local IP address"
    echo "Available network interfaces:"
    ifconfig | grep -E "inet [0-9]+" | grep -v "127.0.0.1"
    exit 1
fi

echo "✅ Detected local IP: $LOCAL_IP"

echo "🔑 Generating $SECRETS_FILE for Local development"

# Generate Secrets.swift with auto-detected IP
cat >"$SECRETS_FILE" <<EOF
import Foundation

// WARNING:
// This code is generated by ./Scripts/generate-secrets-local.sh for Local development.
// Do not edit this file directly. Your changes will be lost on next build.
// Git does not track this file.
// For Local builds, the IP addresses are auto-detected from your network interfaces.
// For other environments, edit the .env file and run ./Scripts/generate-secrets.sh

// swiftlint:disable all

/// Secrets are generated automatically for Local development
enum Secrets {
    static let CONVOS_API_BASE_URL = "http://$LOCAL_IP:4000/api"
    static let XMTP_CUSTOM_HOST = "$LOCAL_IP"
EOF

# Check if .env file exists and add any additional secrets from it
if [ -f ".env" ]; then
    echo "📋 Adding additional secrets from .env file..."

    # Read each line from .env file, handles missing newline at EOF
    while IFS='=' read -r key value || [[ -n "$key" ]]; do
        # Skip comments and empty lines
        [[ $key =~ ^#.*$ ]] && continue
        [[ -z $key ]] && continue

        # Skip the IP-related keys since we're auto-generating them
        [[ "$key" == "CONVOS_API_BASE_URL" ]] && continue
        [[ "$key" == "XMTP_CUSTOM_HOST" ]] && continue

        # Remove any quotes from the value
        value=$(echo "$value" | sed -e 's/^"//' -e 's/"$//')

        # Add the secret to the Swift file
        echo "    static let $key = \"$value\"" >>"$SECRETS_FILE"
    done <.env
else
    echo "⚠️  No .env file found, only generating IP-based secrets"
fi

# Close the enum and add SwiftLint enable comment
cat >>"$SECRETS_FILE" <<'EOF'
}

// swiftlint:enable all
EOF

echo "🏁 Generated $SECRETS_FILE with IP: $LOCAL_IP"
echo "🔗 CONVOS_API_BASE_URL: http://$LOCAL_IP:4000/api"
echo "🌐 XMTP_CUSTOM_HOST: $LOCAL_IP"
