name: ConvosCore Tests

on:
  pull_request:
    paths:
      - 'ConvosCore/**'
      - '.github/workflows/convos-core-tests.yml'
  push:
    branches:
      - main
      - develop
    paths:
      - 'ConvosCore/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run ConvosCore Tests
    runs-on: macos-15
    timeout-minutes: 15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Select Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app
      
      - name: Show environment
        run: |
          xcodebuild -version
          swift --version
      
      - name: Cache Swift Package dependencies
        uses: actions/cache@v4
        with:
          path: |
            ConvosCore/.build
            ~/Library/Caches/org.swift.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('ConvosCore/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      
      - name: Resolve dependencies
        working-directory: ConvosCore
        run: swift package resolve
      
      - name: Run tests on iOS Simulator
        working-directory: ConvosCore
        run: |
          set -o pipefail
          xcodebuild test \
            -scheme ConvosCore \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=26.0' \
            -enableCodeCoverage YES \
            -resultBundlePath TestResults.xcresult \
            | tee test-output.log
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            ConvosCore/TestResults.xcresult
            ConvosCore/test-output.log
          retention-days: 7
      
      - name: Check test status
        if: failure()
        run: |
          echo "❌ Tests failed! Check the uploaded artifacts for details."
          exit 1

