name: SwiftLint

on:
  workflow_dispatch: # ← optional, to run manually
  pull_request:
    branches: ['main', 'dev']
  push:
    branches: ['main', 'dev']

jobs:
  SwiftLint:
    name: SwiftLint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        # --strict makes warnings fail the job
        run: swiftlint lint --strict
