name: SwiftLint

on:
  pull_request:
    branches:
      - main
      - joe/main

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        # --strict makes warnings fail the job
        run: swiftlint lint --strict