name: SwiftLint

on:
  workflow_dispatch: # ← optional, to run manually
  pull_request:
    branches: ['main', 'dev']
  push:
    branches: ['main', 'dev']

jobs:
  SwiftLint:
    name: SwiftLint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install SwiftLint 0.61.0
        run: |
          brew uninstall swiftlint || true
          brew install swiftlint@0.61.0
          brew link --overwrite swiftlint@0.61.0

      - name: Run SwiftLint
        # --strict makes warnings fail the job
        run: swiftlint lint --strict
