#!/usr/bin/env bash
set -o errexit -o pipefail -o nounset

# git diff --diff-filter=d --staged --name-only | grep -e '\(.*\).swift$' | while read line; do
#   swiftformat --verbose --config .swiftformat "${line}";
#   git add "$line";
# done
